export const datademo = [
  { user: "@JohnSmith1" },
  { user: "@Alice_Wndr" },
  { user: "@David_Lee" },
  { user: "@SophiaGc13" },
  { user: "@Ella_Mart" },
  { user: "@DanielJms" },
  { user: "@Olivia_Pk" },
  { user: "@Noah_Coop" },
  { user: "@Ava_Wllm" },
  { user: "@Liam_Walk" },
  { user: "@Mia_Tylr" },
  { user: "@EthanCk15" },
  { user: "@EmmaGrcia" },
  { user: "@MichaelJck" },
  { user: "@IsabellaLz" },
  { user: "@WilliamRdz" },
  { user: "@Emily_Mrtz" },
  { user: "@James_Thms" },
  { user: "@SofiaAndrs" },
  { user: "@Ben_Morris" },
];
